set(QV2RAY_BASEDIR_COMPONENTS ${CMAKE_SOURCE_DIR}/src/components)
set(QV2RAY_BASEDIR_CORE ${CMAKE_SOURCE_DIR}/src/core)
set(QV2RAY_BASEDIR_BASE ${CMAKE_SOURCE_DIR}/src/base)

set(QV2RAY_BASE_SOURCES
    ${QV2RAY_BASEDIR_BASE}/Qv2rayBaseApplication.cpp
    ${QV2RAY_BASEDIR_BASE}/Qv2rayBaseApplication.h
    # Platform Dependent UI
    ${CMAKE_SOURCE_DIR}/src/ui/Qv2rayPlatformApplication.cpp
    ${CMAKE_SOURCE_DIR}/src/ui/Qv2rayPlatformApplication.h
    #
    ${QV2RAY_BASEDIR_BASE}/JsonHelpers.h
    ${QV2RAY_BASEDIR_BASE}/models/CoreObjectModels.h
    ${QV2RAY_BASEDIR_BASE}/models/QvComplexConfigModels.h
    ${QV2RAY_BASEDIR_BASE}/models/QvConfigIdentifier.h
    ${QV2RAY_BASEDIR_BASE}/models/QvCoreSettings.h
    ${QV2RAY_BASEDIR_BASE}/models/QvRuntimeConfig.h
    ${QV2RAY_BASEDIR_BASE}/models/QvSafeType.h
    ${QV2RAY_BASEDIR_BASE}/models/QvSettingsObject.h
    ${QV2RAY_BASEDIR_BASE}/models/QvStartupConfig.h
    #
    ${QV2RAY_BASEDIR_BASE}/Qv2rayBase.h
    ${QV2RAY_BASEDIR_BASE}/Qv2rayFeatures.h
    ${QV2RAY_BASEDIR_BASE}/Qv2rayLog.h
    #
    ${CMAKE_SOURCE_DIR}/src/utils/HTTPRequestHelper.cpp
    ${CMAKE_SOURCE_DIR}/src/utils/HTTPRequestHelper.h
    ${CMAKE_SOURCE_DIR}/src/utils/QvHelpers.cpp
    ${CMAKE_SOURCE_DIR}/src/utils/QvHelpers.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/geosite/QvGeositeReader.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/geosite/QvGeositeReader.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/LatencyTest.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/LatencyTest.h
    ${QV2RAY_BASEDIR_COMPONENTS}/translations/QvTranslator.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/translations/QvTranslator.h
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/LatencyTestThread.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/LatencyTestThread.h
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/TCPing.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/TCPing.h
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/RealPing.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/RealPing.h
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/DNSBase.h
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/win/ICMPPing.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/win/ICMPPing.h
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/unix/ICMPPing.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/latency/unix/ICMPPing.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/ntp/QvNTPClient.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/ntp/QvNTPClient.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/plugins/QvPluginHost.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/plugins/QvPluginHost.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/port/QvPortDetector.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/port/QvPortDetector.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/proxy/QvProxyConfigurator.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/proxy/QvProxyConfigurator.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/route/RouteSchemeIO.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/route/RouteSchemeIO.h
    #
    ${QV2RAY_BASEDIR_COMPONENTS}/update/UpdateChecker.cpp
    ${QV2RAY_BASEDIR_COMPONENTS}/update/UpdateChecker.h
    #
    ${QV2RAY_BASEDIR_CORE}/connection/ConnectionIO.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/ConnectionIO.h
    ${QV2RAY_BASEDIR_CORE}/connection/Generation.h
    ${QV2RAY_BASEDIR_CORE}/connection/generation/final.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/generation/inbounds.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/generation/outbounds.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/generation/filters.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/generation/routing.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/generation/misc.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/Serialization.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/Serialization.h
    ${QV2RAY_BASEDIR_CORE}/connection/serialization/ss.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/serialization/ssd.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/serialization/vmess.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/serialization/vmess_new.cpp
    ${QV2RAY_BASEDIR_CORE}/connection/serialization/vless.cpp
    #
    ${QV2RAY_BASEDIR_CORE}/CoreUtils.cpp
    ${QV2RAY_BASEDIR_CORE}/CoreUtils.h
    #
    ${QV2RAY_BASEDIR_CORE}/handler/ConfigHandler.cpp
    ${QV2RAY_BASEDIR_CORE}/handler/ConfigHandler.h
    ${QV2RAY_BASEDIR_CORE}/handler/KernelInstanceHandler.cpp
    ${QV2RAY_BASEDIR_CORE}/handler/KernelInstanceHandler.h
    ${QV2RAY_BASEDIR_CORE}/handler/RouteHandler.cpp
    ${QV2RAY_BASEDIR_CORE}/handler/RouteHandler.h
    #
    ${QV2RAY_BASEDIR_CORE}/kernel/APIBackend.cpp
    ${QV2RAY_BASEDIR_CORE}/kernel/APIBackend.h
    ${QV2RAY_BASEDIR_CORE}/kernel/QvKernelABIChecker.cpp
    ${QV2RAY_BASEDIR_CORE}/kernel/QvKernelABIChecker.h
    ${QV2RAY_BASEDIR_CORE}/kernel/V2RayKernelInteractions.cpp
    ${QV2RAY_BASEDIR_CORE}/kernel/V2RayKernelInteractions.h
    #
    ${QV2RAY_BASEDIR_CORE}/settings/SettingsBackend.cpp
    ${QV2RAY_BASEDIR_CORE}/settings/SettingsBackend.h
    ${QV2RAY_BASEDIR_CORE}/settings/SettingsUpgrade.cpp
    )
