option(USE_SYSTEM_UVW "Use system libuvw" OFF)

if(USE_SYSTEM_UVW)
    find_package(libuv REQUIRED)
    add_library(Qv2ray::libuv ALIAS libuv::uv)
    find_package(uvw CONFIG REQUIRED)
    add_library(Qv2ray_uvw INTERFACE)
    target_link_libraries(Qv2ray_uvw INTERFACE uvw::uvw)
    target_link_libraries(Qv2ray_uvw INTERFACE Qv2ray::libuv)
    add_library(Qv2ray::libuvw ALIAS Qv2ray_uvw)
else()
    set(BUILD_UVW_LIBS ON)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/uvw)
    add_library(Qv2ray::libuvw ALIAS uvw)
endif()
